version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v3-deps-{{ .Branch }}
            - v3-deps
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v3-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - run: yarn typecheck
      - run: yarn lint
      - run:
          command: yarn start
          background: true
      - run: npx wait-on http://localhost:8000
      #- run: $(yarn bin)/cypress run --record --key $RECORD_KEY --reporter junit --reporter-options 'mochaFile=junit/test-results.xml'
      - run: $(yarn bin)/cypress run --reporter junit --reporter-options 'mochaFile=junit/test-results.xml'
      - store_test_results:
          path: junit
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
